name: test

on:
  push:

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Lint
        run: |
          gofmt -d . | if [$(wc -l) != 0 ]; then exit 1; fi

      - name: Test
        run: |
          go test ./...
